In [1]:
import pandas as pd

In [17]:
data=pd.read_excel('./8.31数据处理.xlsx')

In [4]:
!pip install openpyxl -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 1.6 MB/s eta 0:00:00a 0:00:01


In [18]:
data_=data.copy()
data_=data_.T

In [20]:
data_=data_.drop(["id"],axis=0)

In [13]:
#归一化模块倒入
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [21]:
#按行归一化
bzh=MinMaxScaler()
data_=bzh.fit_transform(data_)

In [24]:
data_.T

array([[1.        , 0.91509434, 0.        , 0.8490566 ],
       [0.57438017, 0.        , 1.        , 0.24586777],
       [1.        , 0.        , 0.44253979, 0.00542242],
       ...,
       [1.        , 0.        , 0.2675367 , 0.02555737],
       [0.33138402, 1.        , 0.        , 0.58187135],
       [0.51755027, 0.        , 1.        , 0.07513711]])

In [25]:
data[["Q","A","B","C"]]=data_.T

In [26]:
data

id         Q         A         B         C
0      ENSDARG00000000001  1.000000  0.915094  0.000000  0.849057
1      ENSDARG00000000002  0.574380  0.000000  1.000000  0.245868
2      ENSDARG00000000018  1.000000  0.000000  0.442540  0.005422
3      ENSDARG00000000019  0.876864  1.000000  0.000000  0.910899
4      ENSDARG00000000068  1.000000  0.742747  0.000000  0.239845
...                   ...       ...       ...       ...       ...
26106         XLOC_033107  1.000000  0.000000  0.725490  0.281046
26107         XLOC_033125  0.177554  1.000000  0.000000  0.520938
26108         XLOC_033134  1.000000  0.000000  0.267537  0.025557
26109         XLOC_033168  0.331384  1.000000  0.000000  0.581871
26110         XLOC_033170  0.517550  0.000000  1.000000  0.075137

[26111 rows x 5 columns]

In [29]:
import numpy as np

In [32]:
np.corrcoef(data_.T).shape

(26111, 26111)

In [33]:
data_corr=np.corrcoef(data_.T)

In [35]:
index_id=data["id"].values

In [71]:
pd.DataFrame(data_corr,columns=index_id,index=index_id)

ENSDARG00000000001  ENSDARG00000000002  \
ENSDARG00000000001            1.000000           -0.786533   
ENSDARG00000000002           -0.786533            1.000000   
ENSDARG00000000018            0.006073            0.584829   
ENSDARG00000000019            0.980033           -0.891143   
ENSDARG00000000068            0.805455           -0.453063   
...                                ...                 ...   
XLOC_033107                  -0.237517            0.785829   
XLOC_033125                   0.588304           -0.949417   
XLOC_033134                   0.196756            0.428387   
XLOC_033168                   0.711658           -0.981349   
XLOC_033170                  -0.806636            0.985868   

                    ENSDARG00000000018  ENSDARG00000000019  \
ENSDARG00000000001            0.006073            0.980033   
ENSDARG00000000002            0.584829           -0.891143   
ENSDARG00000000018            1.000000           -0.191872   
ENSDARG00000000019           -0.191872            1.000000   
ENSDARG00000000068            0.437192            0.711958   
...                                ...                 ...   
XLOC_033107                   0.940136           -0.423822   
XLOC_033125                  -0.695042            0.722909   
XLOC_033134                   0.981204           -0.001627   
XLOC_033168                  -0.598234            0.823876   
XLOC_033170                   0.585902           -0.907743   

                    ENSDARG00000000068  ENSDARG00000000069  \
ENSDARG00000000001            0.805455            0.099570   
ENSDARG00000000002           -0.453063            0.212517   
ENSDARG00000000018            0.437192            0.710870   
ENSDARG00000000019            0.711958           -0.028993   
ENSDARG00000000068            1.000000            0.669762   
...                                ...                 ...   
XLOC_033107                   0.118975            0.478800   
XLOC_033125                   0.336913           -0.153882   
XLOC_033134                   0.570446            0.695563   
XLOC_033168                   0.459139           -0.105441   
XLOC_033170                  -0.401074            0.327674   

                    ENSDARG00000000086  ENSDARG00000000103  \
ENSDARG00000000001            0.956849            0.810296   
ENSDARG00000000002           -0.632795           -0.306355   
ENSDARG00000000018            0.126692            0.587093   
ENSDARG00000000019            0.908544            0.680284   
ENSDARG00000000068            0.715830            0.931485   
...                                ...                 ...   
XLOC_033107                  -0.050365            0.339738   
XLOC_033125                   0.370861            0.097238   
XLOC_033134                   0.314364            0.728052   
XLOC_033168                   0.512666            0.250034   
XLOC_033170                  -0.695993           -0.310773   

                    ENSDARG00000000142  ENSDARG00000000151  ...  XLOC_032643  \
ENSDARG00000000001            0.937208            0.725846  ...     0.205600   
ENSDARG00000000002           -0.567562           -0.153431  ...     0.422678   
ENSDARG00000000018            0.203939            0.612039  ...     0.978913   
ENSDARG00000000019            0.873536            0.584697  ...     0.007219   
ENSDARG00000000068            0.724256            0.716637  ...     0.570750   
...                                ...                 ...  ...          ...   
XLOC_033107                   0.032566            0.476705  ...     0.882059   
XLOC_033125                   0.296014           -0.128767  ...    -0.579670   
XLOC_033134                   0.386978            0.747628  ...     0.999856   
XLOC_033168                   0.443872            0.033974  ...    -0.458405   
XLOC_033170                  -0.634061           -0.221103  ...     0.412503   

                    XLOC_032675  XLOC_032677  XLOC_032691  XLOC_032699  \
ENSDA

In [40]:
data_corr

array([[ 1.        , -0.7865326 ,  0.00607334, ...,  0.19675578,
         0.71165763, -0.80663647],
       [-0.7865326 ,  1.        ,  0.58482863, ...,  0.42838736,
        -0.9813494 ,  0.98586771],
       [ 0.00607334,  0.58482863,  1.        , ...,  0.98120416,
        -0.59823449,  0.58590155],
       ...,
       [ 0.19675578,  0.42838736,  0.98120416, ...,  1.        ,
        -0.46093895,  0.42078361],
       [ 0.71165763, -0.9813494 , -0.59823449, ..., -0.46093895,
         1.        , -0.93609093],
       [-0.80663647,  0.98586771,  0.58590155, ...,  0.42078361,
        -0.93609093,  1.        ]])

In [42]:
mask=np.tri(26111,k=-1)

In [44]:
mask=mask.astype(bool)

data_corr[mask]

array([-0.7865326 ,  0.00607334,  0.58482863, ..., -0.89411172,
        0.42078361, -0.93609093])

In [47]:
mask.sum()

340879105

In [46]:
data_corr[mask].shape

(340879105,)

In [48]:
data_corrmask=data_corr[mask]

In [49]:
np.sum(data_corrmask>0.8)


63080074

In [50]:
print(63080074/340879105)

0.18505116058668367


In [51]:
np.sum(data_corrmask<-0.8)

20607739

In [52]:
print(20607739/340879105)

0.060454685246841396


In [53]:
#聚类
from sklearn.cluster import KMeans 

In [55]:
data_.shape

(4, 26111)

In [58]:
data_kmeans=KMeans(n_clusters=30)

In [59]:
data_kmeans.fit(data_.T)

/Users/sunqian/anaconda3/envs/ICR/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=30)

In [65]:
data_kmeans.transform(data_.T)

array([[0.51802489, 1.47748003, 0.92464821, ..., 0.10952487, 1.13105834,
        0.75980219],
       [1.53330382, 0.39767075, 1.13695214, ..., 1.54093881, 0.71814642,
        1.32935833],
       [1.47841306, 0.49557641, 0.57060753, ..., 1.35720267, 0.33657338,
        0.92446375],
       ...,
       [1.42296382, 0.66343348, 0.45733611, ..., 1.29717854, 0.35528892,
        0.86419203],
       [0.38176412, 1.54396082, 1.0323006 , ..., 0.64695615, 1.29970716,
        0.82242723],
       [1.61412107, 0.43143017, 1.14921271, ..., 1.63163982, 0.79323854,
        1.33925737]])

In [61]:
data_kmeans.transform(data_.T).shape

(26111, 30)

In [63]:
data_kmeans.predict(data_.T)

array([27,  5,  7, ..., 21, 26,  5], dtype=int32)

In [68]:
data["cluster_class"]=data_kmeans.predict(data_.T)



In [64]:
data_kmeans.predict(data_.T).shape

(26111,)

In [66]:
data_kmeans.cluster_centers_

array([[ 4.88111161e-01,  9.39560033e-01, -3.88578059e-16,
         9.24694123e-01],
       [ 9.39306032e-01,  2.88762514e-02,  9.21931472e-01,
         1.11545019e-01],
       [ 1.00000000e+00,  3.85895161e-01,  3.11085515e-02,
         9.14585533e-02],
       [ 5.05403908e-01,  1.00000000e+00,  4.49333695e-02,
         1.30748915e-01],
       [ 3.67558375e-02,  4.28899456e-02,  3.45725250e-02,
         1.00000000e+00],
       [ 5.45217705e-01,  4.81851979e-02,  1.00000000e+00,
         9.62882554e-02],
       [ 1.00000000e+00,  4.79336893e-01, -3.33066907e-16,
         4.19336095e-01],
       [ 1.00000000e+00,  7.50279700e-02,  5.27624171e-01,
         3.29607894e-02],
       [ 7.09166458e-01,  5.87101963e-01, -3.88578059e-16,
         1.00000000e+00],
       [ 8.48282938e-01,  9.06257946e-01,  6.62881605e-01,
        -2.77555756e-16],
       [ 1.09042822e-01,  1.38189401e-01,  9.08626429e-01,
         8.19645145e-01],
       [ 8.97385824e-02,  9.35378640e-01,  1.09923323e-01,
      

In [70]:
#聚类结果导出
data.to_excel("data_cluster.xlsx",index=None)
